---
name: Pod-ToDemo
version: 1.00
author: ~
abstract: writes a demo program from a tutorial POD
license: perl
requires:
  Test::Exception: ''
  Test::Simple: 0.47
provides:
  Pod::ToDemo:
    file: lib/Pod/ToDemo.pm
    version: 1.00
generated_by: Module::Build version 0.2611
