--- #YAML:1.0
name: Pod-ToDemo
version: 0.22
author: ~
abstract: writes a demo program from a tutorial POD
license: perl
requires:
  Test::Exception: ''
  Test::Simple: 0.47
provides:
  Pod::ToDemo:
    file: lib/Pod/ToDemo.pm
    version: 0.22
generated_by: Module::Build version 0.2607
